#!/usr/bin/env zsh

list_dir=~/.lists
timestamp=$(date +%s)

export dotfiles_dir=~/.dotfiles
export fzf_dir=~/.fzf
export list_file_apt_packages=${list_dir}/apt-packages.txt
export list_file_brew_casks=${list_dir}/brew-casks.txt
export list_file_brew_packages=${list_dir}/brew-packages.txt
export list_file_bun_packages=${list_dir}/bun-packages.txt
export list_file_uv_tools=${list_dir}/uv-tools.txt
export list_file_winget_packages=${list_dir}/winget-packages.txt
export zgen_dir=~/.zgenom
export copy_dir=~/.dotfiles/copy

if grep -qi microsoft /proc/version 2>/dev/null; then
  export win_appdata_local="/mnt/c/Users/$(cmd.exe /C 'echo %USERNAME%' 2>/dev/null | tr -d '\r')/AppData/Local"
fi
