#!/usr/bin/env zsh

while :; do
  price=$(
    curl \
      'https://query1.finance.yahoo.com/v8/finance/chart/GME?region=US&lang=en-US&includePrePost=false&interval=2m&useYfid=true&range=1d&corsDomain=finance.yahoo.com&.tsrc=finance' \
      -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0' \
      -H 'Accept: */*' \
      -H 'Accept-Language: en-US,en;q=0.5' \
      -H 'Referer: https://finance.yahoo.com/quote/GME' \
      -H 'Origin: https://finance.yahoo.com' \
      -H 'DNT: 1' \
      -H 'Connection: keep-alive' \
      -H 'Cookie: A1=d=AQABBJxYjmICEAbfuj8EM4lKiAXC6m8L2mUFEgEBAQGqj2KYYgAAAAAA_eMAAA&S=AQAAAoCjEe4oZEv7jxlSphDRC6I; A3=d=AQABBJxYjmICEAbfuj8EM4lKiAXC6m8L2mUFEgEBAQGqj2KYYgAAAAAA_eMAAA&S=AQAAAoCjEe4oZEv7jxlSphDRC6I; A1S=d=AQABBJxYjmICEAbfuj8EM4lKiAXC6m8L2mUFEgEBAQGqj2KYYgAAAAAA_eMAAA&S=AQAAAoCjEe4oZEv7jxlSphDRC6I&j=US; GUC=AQEBAQFij6pimEIhTATO; cmp=t=1653499629&j=0&u=1---; PRF=t%3DGME' \
      -H 'Sec-Fetch-Dest: empty' \
      -H 'Sec-Fetch-Mode: cors' \
      -H 'Sec-Fetch-Site: same-site' \
      -H 'TE: trailers' \
      -s | \
      grep -Eo 'regularMarketPrice":[^,]+' | \
      cut -d: -f 2
  )

  color="\033[0m"

  if [[ -n "$previous" ]]; then
    if [[ $(echo "${price}>${previous}" | bc -l) -eq 1 ]]; then
      color="\033[1;32m"
    elif [[ $(echo "${price}<${previous}" | bc -l) -eq 1 ]]; then
      color="\033[1;31m"
    fi
  fi

  echo -en "${color}\$${price}  \r"
  previous="$price"
  sleep 2
done
