#!/usr/bin/env zsh

date=$(date '+%Y-%m-%d')
dir=~/.journal
email=gpg@cade.me
readme=README.md
tarball=data.tgz.gpg

mkdir -p $dir
cd $dir

if [[ $1 == "commit" ]]; then
  if [[ -f $tarball ]]; then
    echo "tarball already exists... bailing!"
    exit 1
  fi

  find . \
    -depth 1 \
    -type f \
    ! -name $tarball \
    ! -name $readme \
    | tar cvf - -T - \
    | gzip -9 \
    | gpg -er $email -o $tarball

  git add $tarball

  if git log --pretty=format:"%s" | grep -qF $date; then
    git commit --amend --no-edit
    git push -f
  else
    git commit -m $date
    git push
  fi

  find . \
    -depth 1 \
    -type f \
    ! -name $tarball \
    ! -name $readme \
    -exec rm -f {} +
  exit
fi

if [[ -f $tarball ]]; then
  gpg $tarball || exit 1
  decrypted=${tarball%.gpg}
  tar xvf $decrypted || exit 1
  rm -f $tarball $decrypted
fi

if [[ ! -f $date ]]; then
cat > $date << EOL
What am I grateful for?
What do I want to accomplish today?
What obstacles I am going to face today?
How do I want to react to those obstacles?
Did I do the things I said I was going to do?
Did I act virtuously today? If not, how can I do better next time?
What did I do wrong and how can I fix it?
General notes?
EOL
fi

$EDITOR $date
