#!/bin/sh

candidates="
/opt/homebrew/bin/pinentry-mac
/usr/local/bin/pinentry-mac
/usr/bin/pinentry-mac
/usr/bin/pinentry-curses
/bin/pinentry-curses
/usr/bin/pinentry-tty
/bin/pinentry-tty
/usr/bin/pinentry
/bin/pinentry
"

for p in $candidates; do
  if [ -x "$p" ]; then
    exec "$p" "$@"
  fi
done

echo "Error: No pinentry program found." >&2
exit 1
