#!/usr/bin/env zsh

source "$(dirname "$0")/utilities/config"
source "$(dirname "$0")/utilities/fancy-print"

fancy_print "updating brew packages..."
brew upgrade

fancy_print "updating npm packages..."
bun update -g

fancy_print "updating python packages..."
xargs python3 -m pip install -U < "${list_file_python_packages}"

fancy_print "updating neovim plugins..."
nvim -c 'PlugUpgrade' -c 'PlugUpdate' -c 'UpdateRemotePlugins' -c 'qa!'
