#!/usr/bin/env zsh

source "$(dirname "$0")/utilities/config"
source "$(dirname "$0")/utilities/fancy-print"

fancy_print "updating brew packages..."
brew upgrade

fancy_print "updating brew casks..."
brew upgrade --casks

fancy_print "cleaning up brew packages..."
brew cleanup

fancy_print "updating bun packages..."
xargs bun i -g < "${list_file_bun_packages}"

fancy_print "updating uv tools..."
uv tool upgrade --all

fancy_print "updating neovim plugins..."
nvim -c 'PlugUpgrade' -c 'PlugUpdate' -c 'UpdateRemotePlugins' -c 'qa!'
