#!/usr/bin/env zsh

set -e

while [[ $# -gt 0 ]]; do
  key="$1"

  case "$key" in
    -w|--wordlist) WORDLIST="$2" && shift && shift ;;
    *) shift ;;
  esac
done

if [[ -z "$WORDLIST" ]] || [[ ! -f "$WORDLIST" ]]; then
  echo "ERROR: please specify a valid wordlist (-w|--wordlist)" 1>&2
  exit 1
fi

for word in $(shuf "$WORDLIST"); do
  read -rp "$word"
  open "https://www.merriam-webster.com/dictionary/${word}"
  sleep 2
done
